"""empty message

Revision ID: 26690699444e
Revises: 6770106543f3
Create Date: 2026-08-10 17:16:49.038294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26690699444e'
down_revision = '6770106543f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
